export const headerLinks = [
  { title: "Features", path: "/" },
  { title: "Integrations", path: "/" },
  { title: "Customers", path: "/" },
  { title: "Pricing", path: "/" },
];
export const robotDefaultValues = {
  name: "",
  version: "",
  description: "",
  strategy: "",
  active: true,
  categoryId: "",
  symbols: [],
  socket: "",
};

export const accountDefaultValues = {
  account_name: "",
  email: "",
  token: "",
  active: true,
  balance: 0,
  opening_balance: 0,
  account_type: "PRACTICE",
};

export const connectionDefaultValues = {
  accountId: "",
  robotId: "",
  categoryId: "",

  payout: 0,
  stake: 0.45,
  currency: "",

  expiration: 0,
  current_level: 1,
  active_contract_id: 0,

  last_profit: 0,
  target_percentage: 0,
  entry: "",

  martingale: true,
  active: false,
  target_reached: false,
  open_trade: false,
  dynamic_stake: false,

  stop_loss: 0,
  stake_percentage: 0,
  risk_type: "FLAT",
  risk_percentage: 0,
};

export const signalDefaultValues = {
  signalCategoryId: "",
  symbol: "",
  entry_range: "",
  stop_loss: 0,
  take_profit_1: 0,
  take_profit_2: 0,
  take_profit_3: 0,
  take_profit_4: 0,
  take_profit_5: 0,
  is_premium: false,
  is_active: true,
  profit: 0,
};

export const symbols = {
  forex: [
    { name: "AUDCAD", active: true },
    { name: "AUDCHF", active: true },
    { name: "AUDJPY", active: true },
    { name: "AUDNZD", active: true },
    { name: "AUDUSD", active: true },
    { name: "CADCHF", active: true },
    { name: "CADJPY", active: true },
    { name: "CHFJPY", active: true },
    { name: "EURAUD", active: true },
    { name: "EURCAD", active: true },
    { name: "EURCHF", active: true },
    { name: "EURGBP", active: true },
    { name: "EURJPY", active: true },
    { name: "EURNZD", active: true },
    { name: "EURUSD", active: true },
    { name: "GBPAUD", active: true },
    { name: "GBPCAD", active: true },
    { name: "GBPCHF", active: true },
    { name: "GBPJPY", active: true },
    { name: "GBPNZD", active: true },
    { name: "GBPUSD", active: true },
    { name: "NZDCAD", active: true },
    { name: "NZDCHF", active: true },
    { name: "NZDJPY", active: true },
    { name: "NZDUSD", active: true },
    { name: "USDCAD", active: true },
    { name: "USDCHF", active: true },
    { name: "USDCNH", active: true },
    { name: "USDDKK", active: true },
    { name: "USDHKD", active: true },
    { name: "USDJPY", active: true },
    { name: "USDMXN", active: true },
    { name: "USDNOK", active: true },
    { name: "USDSEK", active: true },
    { name: "USDSGD", active: true },
    { name: "USDTHB", active: true },
    { name: "USDTRY", active: true },
    { name: "USDZAR", active: true },
    { name: "XAUUSD", active: true },
  ],
  synthetic: [
    { name: "BOOM 300", active: true },
    { name: "BOOM 500", active: true },
    { name: "BOOM 1000", active: true },
    { name: "CRASH 300", active: true },
    { name: "CRASH 500", active: true },
    { name: "CRASH 1000", active: true },
    { name: "STEP INDEX", active: true },
    { name: "VOLATILITY INDICES 10", active: true },
    { name: "VOLATILITY INDICES 10 (1s)", active: true },
    { name: "VOLATILITY INDICES 25", active: true },
    { name: "VOLATILITY INDICES 25 (1s)", active: true },
    { name: "VOLATILITY INDICES 50", active: true },
    { name: "VOLATILITY INDICES 50 (1s)", active: true },
    { name: "VOLATILITY INDICES 75", active: true },
    { name: "VOLATILITY INDICES 75 (1s)", active: true },
    { name: "VOLATILITY INDICES 100", active: true },
    { name: "VOLATILITY INDICES 100 (1s)", active: true },
  ],
};
